### ISSUE TITLE
Create .gitignore to enforce removal of DS_Store and other unwanted files

### ISSUE THREAD

**Issue by napulen** [ELVIS-Project/Madrigal-Project#3]
Just looking at the commits and seeing that `.DS_Store` seemed to be a problem.

One way to get them out of the way for good is to create a `.gitignore` file.

Any commits will not include the ignored files in the future.

This is also helpful for ignoring intermediate files (e.g., MuseScore temporary files).

**Comment by julieemelyncumming** [comment]
Thanks Nestor!  Sylvain – I’m just bringing this to your attention.

Julie

Julie E. Cumming
McGill University, Schulich School of Music
***@***.***

From: Néstor Nápoles López ***@***.***>
Sent: July 15, 2021 10:59 AM
To: ELVIS-Project/Madrigal-Project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ELVIS-Project/Madrigal-Project] Create .gitignore to enforce removal of DS_Store and other unwanted files (#3)


Just looking at the commits and seeing that .DS_Store seemed to be a problem.

One way to get them out of the way for good is to create a .gitignore file.

Any commits will not include the ignored files in the future.

This is also helpful for ignoring intermediate files (e.g., MuseScore temporary files).

**Comment by emilyhopkins** [comment]
I can do this one 
and thanks @napulen for the suggestion!
